baseURL = "https://www.richardpalacios.dev/"
languageCode = "en-us"
title = "Digital Garden de Richard Palacios G."
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "dracula"

rssLimit  = 10  # Maximum number of items in the RSS feed.
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message 

# googleAnalytics = ""
disqusShortname = "rpalaciosg"
enableEmoji     = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Richard Palacios G." 

[taxonomies]
  tag      = "tags"
  category = "categories"
  mood = "moods"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "My digital garden, resume, personal blog and portfolio by Richard Palacios García"
  keywords = "Richard Palacios, Richard Palacios Garcia, javascript, ecuador, portfolio, web development, fullstack, homepage, blog, dev, development, programming, software engineer"
  images = [""]

  homeSubtitle = "FullStack Software Engineer"

  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = true

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

   # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = 2024
    rss = true
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
       "&#10084; <a href=\"https://themes.gohugo.io/themes/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"
    ]
  
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "⚡Richard Palacios García"
    subtitle = "FullStack Software Engineer"
    keywords = "FullStack, Web Developer - Richard Palacios, Richard Palacios Garcia, javascript, ecuador, portfolio, web development, fullstack, homepage, blog, dev, development, programming, software engineer"
    #copyright = ""
    readOtherPosts = "Lee otras publicaciones"


[params.logo]
    logoText = "rpalaciosg"
    logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:richardpalacios231@gmail.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/rpalaciosg_"

  [[params.social]]
    name = "github"
    url  = "https://github.com/rpalaciosg"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/richardpalaciosgarcia/"

    [[params.social]]
    name = "hashnode"
    url  = "https://hashnode.com/@rpalaciosg"

#  [[params.social]]
#    name = "Hackerrank"
#    url  = "https://www.hackerrank.com/rpalaciosg?hr_r=1"
  
#  [[params.social]]
#    name = "stackoverflow"
#    url  = "https://www.stackoverflow.com/"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "/About-me"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "/Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "projects"
    name = "/Projects"
    url = "/projects"

# Goldmark
[markup.goldmark.renderer]
      unsafe = true
